# Generated by Django 3.1.5 on 2021-01-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hp', models.IntegerField()),
                ('hpperlevel', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('mpperlevel', models.IntegerField()),
                ('movespeed', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('armorperlevel', models.IntegerField()),
                ('spellblock', models.IntegerField()),
                ('spellblockperlevel', models.IntegerField()),
                ('attackrange', models.IntegerField()),
                ('hpregen', models.IntegerField()),
                ('hpregenperlevel', models.IntegerField()),
                ('mpregen', models.IntegerField()),
                ('mpregenperlevel', models.IntegerField()),
                ('crit', models.IntegerField()),
                ('critperlevel', models.IntegerField()),
                ('attackdamage', models.IntegerField()),
                ('attackdamageperlevel', models.IntegerField()),
                ('attackspeedperlevel', models.IntegerField()),
                ('attackspeed', models.IntegerField()),
            ],
        ),
    ]
