# Generated by Django 3.1.5 on 2021-01-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='armor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='armorperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackdamage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackdamageperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackrange',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackspeed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackspeedperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='crit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='critperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hpperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hpregen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hpregenperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='movespeed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mpperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mpregen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mpregenperlevel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='spellblock',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='spellblockperlevel',
            field=models.FloatField(),
        ),
    ]
