# Generated by Django 3.1.5 on 2021-01-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_auto_20210108_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='sprite',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
